_doc:
  default:
    page-size: a4
    landscape: false
    margins:
      top: 72.0
      left: 72.0
      right: 72.0
      bottom: 72.0
    background: null
    first-page:
      margins:
        top: 72.0
        left: 72.0
        right: 72.0
        bottom: 72.0
      background: null

_style:
  default:
    headings:
      font: Helvetica
      color: "#222222"
      ratio: Major Third
    body:
      font: Helvetica
      color: black
      size: 10 # pts
      spacing: 1.7 # pts
      bullets:
        font: Helvetica
        size: 10
        color: black
        symbols: "•‣⁃∘"
        spacing: 10
        indent-bullet: 20
        indent-text: 40


_tablestyle:
  default:
    cell-padding:
      top: 7.5
      left: 15
      right: 15
      bottom: 7.5
    headers:
      text: 
        font: Helvetica
        size: 12
        color: "#000000"
        bold: True
      row:
        color: "#ffffff"
        lines:
          - above
          - below
    body:
      text:
        font: "Helvetica"
        size: 11
        color: "black"
      rows:
        color:
          even: "#ffffff"
          odd: "#ffffff"
        lines:
          - above



