_tablestyle:
  cell-padding:
    top: 7.5
    left: 15
    right: 15
    bottom: 7.5
    
  headers:
    text: 
      font: Helvetica
      size: 12
      color: "#ffffff"
      bold: True
    row:
      color: "#000000"
      lines:
        - above
        - below
  body:
    text:
      font: "Helvetica"
      size: 11
      color: "black"
    rows:
      color:
        even: "#ffffff"
        odd: "#eeeeee"
      lines:
        - above
        - below