_style:
  headings:
    font: Helvetica
    color: "#222222"
    size: 24 # Optional
  body:
    font: Helvetica
    color: black
    size: 10 # pts
    spacing: 1.5 # pts
    bullets:
      font: Helvetica
      size: 10
      color: black
      symbols: "•‣⁃∘"
      spacing: 10
