_doc:
  page-size: a4
  landscape: false
  margins:
    top: 1
    left: 1
    right: 1
    bottom: 1
  background: null
  first-page:
    cat: here
    margins:
      top: 1
      left: 1
      right: 1
      bottom: 1
    background: null