_tablestyle:
  cell-padding:
    top: 1
    left: 1
    right: 1
    bottom: 1
    
  headers:
    text: 
      font: Helvetica
      size: 13
      color: "000000"
      bold: True
    row:
      color: "ffffff"
      lines:
        - above
        - below
  body:
    text:
      font: "Helvetica"
      size: 11
      color: "black"
    rows:
      color:
        even: "ffffff"
        odd: "eeeeee"
      lines:
        - above
        - below